// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Eiip.PushNotifications.Database.Migrations
{
    [DbContext(typeof(PushNotificationsDbContext))]
    partial class PushNotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TopCase.OlivaTaxi.PushNotifications.Database.Models.FcmToken", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.HasKey("Uid", "Timestamp");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("TopCase.OlivaTaxi.PushNotifications.Database.Models.PassengerToken", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text");

                    b.HasKey("Uid", "Timestamp");

                    b.HasIndex("FcmToken")
                        .IsUnique();

                    b.ToTable("PassengerTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
